In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
array_a = np.array([[1,2,3],[2.0, 3.1, 7.8]])
array_a

array([[1. , 2. , 3. ],
       [2. , 3.1, 7.8]])

In [4]:
array_a.ndim # dimension

2

In [5]:
array_a.dtype # data type

dtype('float64')

In [6]:
array_a.shape # rows,cols

(2, 3)

In [7]:
array_a.size # count of elements

6

In [8]:
array_a[0,2] # access elements via row,col

np.float64(3.0)

In [9]:
array_a[0,-2] # access elements via row,col

np.float64(2.0)

In [10]:
array_a[1:] # 1 row all columns

array([[2. , 3.1, 7.8]])

In [11]:
array_a[:1] # 1 col all rows

array([[1., 2., 3.]])

In [12]:
array_a[0:2,1:3] # take 0,1 row and get 1,2 cols

array([[2. , 3. ],
       [3.1, 7.8]])

In [13]:
array_a[1,1] = 5.0 # 1 row 1 col -- index starts with 0
array_a

array([[1. , 2. , 3. ],
       [2. , 5. , 7.8]])

In [14]:
array_b = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array_c = np.array(
    [[[1,2],[3,4]],[[5,6],[7,8]]]
)
array_c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
array_c.shape

(2, 2, 2)

In [17]:
array_c[0,0,0]

np.int64(1)

In [18]:
array_d = np.zeros(5, dtype = 'int32') # create array with 5 elements which are zeros
array_d

array([0, 0, 0, 0, 0], dtype=int32)

In [19]:
array_e = np.ones((2,2),dtype='int64') # create 2x2 matrix with 1s
array_e

array([[1, 1],
       [1, 1]])

In [20]:
array_custom = np.full((3,3),5) # create custom elements i.e. 5 with 3x3 matrix
array_custom

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
array_random = np.random.rand(3,3) # random elements in 3x3 matrix
array_random

array([[0.52401456, 0.77976201, 0.8593118 ],
       [0.83770661, 0.8449222 , 0.16519015],
       [0.34610039, 0.97572402, 0.81936042]])

In [22]:
array_identity = np.identity(4) # diagonal elements with 1
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
array_add = array_identity+2 # moving results from array_idenity to array_add
array_add

array([[3., 2., 2., 2.],
       [2., 3., 2., 2.],
       [2., 2., 3., 2.],
       [2., 2., 2., 3.]])

## In order to do arthimethic operations matrix should be of same shape

In [24]:
np.cos(array_identity) # cos values

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [25]:
array_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print("min",np.min(array_b))
print("max",np.max(array_b))
print("sum based on rows",np.sum(array_b, axis = 0))

min 1
max 9
sum based on rows [12 15 18]


In [27]:
array_reshape = array_b.reshape(9,1)
array_reshape # rows should have same element count

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
array_vstack = np.vstack((array_b,array_custom))
array_vstack # on top of each other

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
array_hstack = np.hstack((array_b,array_custom))
array_hstack # side by side

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 5, 5, 5],
       [7, 8, 9, 5, 5, 5]])

In [30]:
# Use genfromtxt to get numpy array created from text file
# use delimiter for separation
# diff btw 32 and 64 - int and big int


In [31]:
array_b > 5 # boolean logic check

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [32]:
array_b[array_b > 5] # pass elements > 5 into array_b

array([6, 7, 8, 9])